# Usa a imagem Node.js padrão, mais completa
FROM node:20

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de gerenciamento de pacotes
COPY package*.json ./

# Instala as dependências
RUN npm install

# Expõe a porta do Angular Live Development Server
EXPOSE 4200

# Comando para iniciar o servidor
CMD ["npm", "start"]